<?php 

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6766d0951f6de',
	'title' => 'A1 Academy Settings Page',
	'fields' => array(
		array(
			'key' => 'field_6766d0951e4fb',
			'label' => 'General',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_67695a11b1ac6',
			'label' => 'Dashboard Page',
			'name' => 'a1a_dashboard_page',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Selection A1Academy dashboard page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6766d1916228f',
			'label' => 'After Login Redirect Page',
			'name' => 'a1a_after_login_redirect_page',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_676ed22f30e33',
			'label' => 'Login Preview Image',
			'name' => 'a1a_login_preview_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_67c45734b0ab7',
			'label' => 'Wallet Address',
			'name' => 'a1am_wallet_address',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_676833fd266d9',
			'label' => 'Email Config',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_67683410266da',
			'label' => 'User Verify Email Content',
			'name' => 'a1a_user_verify_email_content',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Chào {user_fullname},

Để hoàn tất quá trình đăng ký, vui lòng nhấp vào liên kết bên dưới để xác nhận địa chỉ email của bạn:

{user_verify_link}

Nếu bạn không thể nhấp vào liên kết, hãy sao chép và dán nó vào trình duyệt của mình.

Trân trọng,

A1 Academy team',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_67c300514c6c6',
			'label' => 'Admin Contact',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_67c300674c6c7',
			'label' => 'Telegram',
			'name' => 'a1am_telegram',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67c3008b4c6c8',
			'label' => 'Discord',
			'name' => 'a1am_discord',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67c300974c6c9',
			'label' => 'Email',
			'name' => 'a1am_email',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67c300a34c6ca',
			'label' => 'Phone',
			'name' => 'a1am_phone',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'a1a-course-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_67bdbe63009b3',
	'title' => 'A1AM Notification Settings',
	'fields' => array(
		array(
			'key' => 'field_67bdbe63f6c8e',
			'label' => 'Content',
			'name' => 'content',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'notification',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6766deb75ebe3',
	'title' => 'Advanced Settings (Course Tax)',
	'fields' => array(
		array(
			'key' => 'field_676ff0f485607',
			'label' => 'Banner',
			'name' => 'banner',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6766deb7fffca',
			'label' => 'Content',
			'name' => 'meta_content',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'course-tax',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6767ec07f0633',
	'title' => 'Advanced User Settings (A1A Course)',
	'fields' => array(
		array(
			'key' => 'field_6767ec08b8c01',
			'label' => 'User Verify Code',
			'name' => 'a1a_user_verify_code',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Auto-generate when register',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6767ed94606f7',
			'label' => 'Verify Status',
			'name' => 'verify_status',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'User has verified (Important for A1A Course)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_67bddea7ac03e',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67bddf1875d41',
			'label' => 'Telegram',
			'name' => 'telegram',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67bddf2075d42',
			'label' => 'Discord ID',
			'name' => 'discord_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_67bc79ffb987c',
	'title' => 'Course Settings',
	'fields' => array(
		array(
			'key' => 'field_67bc7a009ff20',
			'label' => 'Require Premium Role',
			'name' => 'require_premium_role',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Require user login is premium role to view post.',
			'default_value' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'a1a-course',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'course-tax', array(
	0 => 'a1a-course',
), array(
	'labels' => array(
		'name' => 'Course Tax',
		'singular_name' => 'Course Tax',
		'menu_name' => 'Course Tax',
		'all_items' => 'All Course Tax',
		'edit_item' => 'Edit Course Tax',
		'view_item' => 'View Course Tax',
		'update_item' => 'Update Course Tax',
		'add_new_item' => 'Add New Course Tax',
		'new_item_name' => 'New Course Tax Name',
		'parent_item' => 'Parent Course Tax',
		'parent_item_colon' => 'Parent Course Tax:',
		'search_items' => 'Search Course Tax',
		'not_found' => 'No course tax found',
		'no_terms' => 'No course tax',
		'filter_by_item' => 'Filter by course tax',
		'items_list_navigation' => 'Course Tax list navigation',
		'items_list' => 'Course Tax list',
		'back_to_items' => '← Go to course tax',
		'item_link' => 'Course Tax Link',
		'item_link_description' => 'A link to a course tax',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'a1a-course', array(
	'labels' => array(
		'name' => 'A1A Courses',
		'singular_name' => 'A1A Course',
		'menu_name' => 'A1A Courses',
		'all_items' => 'All Courses',
		'edit_item' => 'Edit Course',
		'view_item' => 'View Course',
		'view_items' => 'View Courses',
		'add_new_item' => 'Add New Course',
		'add_new' => 'Add New Course',
		'new_item' => 'New Course',
		'parent_item_colon' => 'Parent Course:',
		'search_items' => 'Search Course',
		'not_found' => 'No a1a course found',
		'not_found_in_trash' => 'No a1a course found in Trash',
		'archives' => 'A1A Course Archives',
		'attributes' => 'A1A Course Attributes',
		'insert_into_item' => 'Insert into a1a course',
		'uploaded_to_this_item' => 'Uploaded to this a1a course',
		'filter_items_list' => 'Filter a1a course list',
		'filter_by_date' => 'Filter a1a course by date',
		'items_list_navigation' => 'A1A Course list navigation',
		'items_list' => 'A1A Course list',
		'item_published' => 'A1A Course published.',
		'item_published_privately' => 'A1A Course published privately.',
		'item_reverted_to_draft' => 'A1A Course reverted to draft.',
		'item_scheduled' => 'A1A Course scheduled.',
		'item_updated' => 'A1A Course updated.',
		'item_link' => 'A1A Course Link',
		'item_link_description' => 'A link to a a1a course.',
	),
	'public' => false,
	'publicly_queryable' => true,
	'show_ui' => true,
	'show_in_nav_menus' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-book-alt',
	'supports' => array(
		0 => 'title',
		1 => 'author',
		2 => 'editor',
		3 => 'thumbnail',
		4 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'course-tax',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'notification', array(
	'labels' => array(
		'name' => 'a1a-notification',
		'singular_name' => 'Notification',
		'menu_name' => 'Notification',
		'all_items' => 'All notification',
		'edit_item' => 'Edit Notification',
		'view_item' => 'View Notification',
		'view_items' => 'View notification',
		'add_new_item' => 'Add New Notification',
		'add_new' => 'Add New Notification',
		'new_item' => 'New Notification',
		'parent_item_colon' => 'Parent Notification:',
		'search_items' => 'Search a1a-notification',
		'not_found' => 'No a1a-notification found',
		'not_found_in_trash' => 'No a1a-notification found in Trash',
		'archives' => 'Notification Archives',
		'attributes' => 'Notification Attributes',
		'insert_into_item' => 'Insert into notification',
		'uploaded_to_this_item' => 'Uploaded to this notification',
		'filter_items_list' => 'Filter a1a-notification list',
		'filter_by_date' => 'Filter a1a-notification by date',
		'items_list_navigation' => 'a1a-notification list navigation',
		'items_list' => 'a1a-notification list',
		'item_published' => 'Notification published.',
		'item_published_privately' => 'Notification published privately.',
		'item_reverted_to_draft' => 'Notification reverted to draft.',
		'item_scheduled' => 'Notification scheduled.',
		'item_updated' => 'Notification updated.',
		'item_link' => 'Notification Link',
		'item_link_description' => 'A link to a notification.',
	),
	'public' => true,
	'exclude_from_search' => true,
	'show_in_menu' => 'edit.php?post_type=a1a-course',
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'comments',
		2 => 'custom-fields',
	),
	'delete_with_user' => false,
) );
} );

add_action( 'acf/init', function() {
	acf_add_options_page( array(
	'page_title' => 'Course Settings',
	'menu_slug' => 'a1a-course-settings',
	'parent_slug' => 'edit.php?post_type=a1a-course',
	'position' => '',
	'redirect' => false,
) );
} );

